// Current Jville Brew Loop sponsors, mirrored from the live site. Logos are
// self-hosted in public/brand/sponsors/ (not hotlinked from Squarespace). `url`
// is each sponsor's best outbound link (website, else booking/social). `blurb`
// is a one-line description pulled from each sponsor's own copy; `tag` is a short
// category shown as a chip on the featured sponsor cards.
//
// THIS LIST GOES STALE AND NOTHING CATCHES IT. It is a hand-kept mirror taken
// off Squarespace in July 2026; the `sponsors` table that actually tracks who
// is paying (tier, amount, status — see /leadership/sponsors) has no logo or
// URL column, so the two can't be joined and the public wall keeps showing
// whoever was here last time somebody edited this file.
//
// The poker sponsor was removed 2026-08-25 because Jacob spotted it on the
// site after they had left — and the entry was ALSO wrong on its own terms:
// it was named "No Limit Pub Poker" while the logo art in it read "SADDLE UP
// POKER". Check names against /leadership/sponsors before a deploy, and if a
// sponsor is dropped, delete the row here AND its file in
// public/brand/sponsors/.
export const SPONSORS = [
  { name: 'Mabuhay Designs & Co', tag: 'Printing & design', logo: '/brand/sponsors/mabuhay.jpg', url: 'http://www.mabuhay.store', blurb: 'Veteran-owned custom printing and design shop in Jacksonville.', description: "Custom apparel printing out of Jacksonville: direct-to-film on tees, hoodies and crewnecks, UV DTF, laser engraving, and a bring-your-own-garment press service. Same-day rush pickup if the order is in by 3pm, and a pickup area that stays open around the clock." },
  { name: 'Cozy Co. Luxe', tag: 'Candles & fragrance', logo: '/brand/sponsors/cozy-co-luxe.jpg', url: 'https://brand.page/cozycoluxeexperiences', blurb: 'Veteran and active-duty-owned candle and fragrance shop downtown. Common scents isn’t so common.', description: "A veteran and active-duty-owned candle and fragrance bar on Mill Avenue, where the making is as much the point as the buying. Custom candles and scents built around bookable experiences rather than a shelf of finished product." },
  { name: 'The Dragon’s Brew Cafe', tag: 'Coffee & kava', logo: '/brand/sponsors/dragons-brew.jpg', url: 'https://www.thedragonsbrewcafe.com/', blurb: 'Specialty coffee and kava bar, handcrafted espresso and 70+ flavors.', description: "Specialty coffee on Richlands Highway built on a veteran-roasted espresso blend made for the cafe, plus a spiced black tea and the only kava bar in Jacksonville. Open at 7 on weekdays, 8 on weekends, and yes, it is a Pokémon GO PokéStop." },
  { name: 'Joyas Detailing Services', tag: 'Auto detailing', logo: '/brand/sponsors/joyas-detailing.jpg', url: 'https://www.instagram.com/joyasdetailingservicesllc/', blurb: 'Veteran-owned auto detailing, restoration, and customization. Precision isn’t optional, it’s standard.', description: "Veteran-owned detailing and customization that goes well past a wash: paint correction, ceramic coating, paint protection film, tint, vinyl wrap and 12-volt electrical work. Cars, trucks, boats and show builds all welcome." },
  { name: 'Good Times Tattoo Co.', tag: 'Tattoo studio', logo: '/brand/sponsors/good-times-tattoo.jpg', url: 'https://www.goodtimestattoonc.com/', blurb: 'Custom tattoo shop, voted 2024 Best of the Best.', description: "A custom tattoo shop on Lejeune Boulevard that works from your idea rather than a flash wall, in a clean and professional studio. Text them for a free quote before you commit to anything permanent." },
  { name: 'Estetica Med Spa', tag: 'Med spa', logo: '/brand/sponsors/estetica.png', url: 'https://conciergeaestheticnc.com/', blurb: 'Jacksonville’s destination for advanced aesthetics and wellness.', description: "A provider-led aesthetics and wellness practice founded and directed by Louis A. Perez, DMSc, PA-C. Injectables, microneedling, laser resurfacing, body contouring, IV hydration and medically supervised weight-loss programs, run like a private clinic rather than a coupon page." },
  { name: 'Pop Smoke Cigars', tag: 'Cigar shop', logo: '/brand/sponsors/pop-smoke.png', url: 'https://popsmokecigars.com/', blurb: 'The only on-base cigar shop serving MCAS New River and Camp Lejeune.', description: "Veteran-owned tobacconist supplying premium cigars, pipes and accessories through MCCS retail on base, including the MCX complex at Camp Lejeune. Built specifically to serve active-duty and retired military rather than the general market." },
  { name: 'Mario & Company Barber Studio', tag: 'Barber studio', logo: '/brand/sponsors/mario-company.png', url: 'https://getsquire.com/booking/book/mario-and-company-barber-studio-jacksonville', blurb: 'Precision cuts and fades. There’s fresh, then there’s Mario & Company fresh.', description: "Two shops on Western Boulevard, open seven days and taking walk-ins, with a team carrying more than thirty years of combined experience since opening in 2019. Military cuts and fades are the bread and butter, alongside beard trims, hot towel and razor shaves." },
  { name: 'Crush Nutrition', tag: 'Teas & shakes', logo: '/brand/sponsors/crush-nutrition.png', url: 'https://www.facebook.com/crushnutrition.nc', blurb: 'Loaded teas and protein shakes. Great energy, great drinks, great people.', description: "Loaded teas, protein shakes, smoothies and coffee on Yopp Road, made with loose leaf tea and built to stay low in sugar and carbs. The egg chairs are worth the trip on their own." },
  { name: 'Dream Entertainment', tag: 'Events & DJ', logo: '/brand/sponsors/dream-entertainment.png', url: 'https://www.dreamentertainmentnc.com/', blurb: 'Full-service event and entertainment company, 16+ years running the party.', description: "A full-service event company covering Jacksonville and Wilmington: DJs and live bands, photography and video, stage and sound, tables and tents, and wedding planning right down to the officiant. One vendor instead of six." },
  { name: 'El Cerro Tacos', tag: 'Mexican food', logo: '/brand/sponsors/el-cerro-tacos.jpg', url: 'https://www.elcerrotacos.com/', blurb: 'Authentic Mexican in Jacksonville and Swansboro. Every bite closer to the streets of Mexico.', description: "Street-style Mexican drawing on the traditions of Jalisco and Michoacán, opened in Jacksonville in 2018 by Erik Leon and Juan Gonzalez, with a second room in Swansboro a year later. It runs in the family: Erik's father opened El Cerro Grande back in 1992." },
]
